### ISSUE TITLE
tv_grab_fr: Tvheadend on Docker 

### ISSUE THREAD

**Issue by Slim1399** [XMLTV/xmltv#179] opened 2022-04-27 22:48 UTC
XMLTV Version: 0.6.1-1
--------------

XMLTV Component?
----------------
tv_grab_fr

Operating System
----------------
Docker on Openmediavault: 5.6.26-1 (Usul)

What happened?
--------------
2022-04-27 22:58:41.000 [   INFO] xmltv: /usr/bin/tv_grab_fr: grab /usr/bin/tv_grab_fr
2022-04-27 22:58:41.001 [   INFO] spawn: Executing "/usr/bin/tv_grab_fr"
2022-04-27 22:58:43.445 [  ERROR] spawn: Use of uninitialized value $c_id in exists at /usr/bin/tv_grab_fr line 294.
2022-04-27 22:58:43.445 [  ERROR] spawn: Use of uninitialized value $c_id in concatenation (.) or string at /usr/bin/tv_grab_fr line 295.
2022-04-27 23:02:40.764 [  ERROR] spawn: Getting listings...: ##################################################
2022-04-27 23:02:41.482 [  ERROR] spawn: Use of uninitialized value $date_string in pattern match (m//) at /usr/bin/tv_grab_fr line 799.
2022-04-27 23:02:41.483 [  ERROR] spawn: Validation failed for type named DayOfMonth declared in package DateTime::Types (/usr/lib/perl5/vendor_perl/DateTime/Types.pm) at line 29 in sub named (eval) with value undef
2022-04-27 23:02:41.483 [  ERROR] spawn: Trace begun at Specio::Exception->new line 57
2022-04-27 23:02:41.483 [  ERROR] spawn: Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named DayOfMonth declared in package DateTime::Types (/usr/lib/perl5/vendor_perl/DateTime/Types.pm) at line 29 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x7f859eb94f70)', 'value', undef) called at (eval 221) line 91
2022-04-27 23:02:41.483 [  ERROR] spawn: DateTime::_check_new_params('year', undef, 'month', undef, 'day', undef, 'hour', undef, 'minute', undef, 'second', undef, 'time_zone', 'Europe/Paris') called at /usr/lib/perl5/vendor_perl/DateTime.pm line 176
2022-04-27 23:02:41.483 [  ERROR] spawn: DateTime::new('DateTime', 'year', undef, 'month', undef, 'day', undef, 'hour', undef, 'minute', undef, 'second', undef, 'time_zone', 'Europe/Paris') called at /usr/bin/tv_grab_fr line 800
2022-04-27 23:02:41.483 [  ERROR] spawn: main::get_datetime_from_xmltv_time(undef) called at /usr/bin/tv_grab_fr line 744
2022-04-27 23:02:41.483 [  ERROR] spawn: main::update_programme_stop_times('ARRAY(0x7f859a53ac30)') called at /usr/bin/tv_grab_fr line 360
2022-04-27 23:02:41.483 [  ERROR] spawn: main::write_listings_data('XMLTV::Writer=HASH(0x7f859cd99ad0)', 'HASH(0x7f859e1b1608)') called at /usr/bin/tv_grab_fr line 77
2022-04-27 23:02:41.661 [   INFO] xmltv: /usr/bin/tv_grab_fr: grab took 241 seconds
2022-04-27 23:02:41.662 [   INFO] xmltv: /usr/bin/tv_grab_fr: parse took 0 seconds
2022-04-27 23:02:41.662 [   INFO] xmltv: /usr/bin/tv_grab_fr:  channels   tot=  111 new=    0 mod=    0
2022-04-27 23:02:41.662 [   INFO] xmltv: /usr/bin/tv_grab_fr:  brands     tot=    0 new=    0 mod=    0
2022-04-27 23:02:41.662 [   INFO] xmltv: /usr/bin/tv_grab_fr:  seasons    tot=    0 new=    0 mod=    0
2022-04-27 23:02:41.662 [   INFO] xmltv: /usr/bin/tv_grab_fr:  episodes   tot=    0 new=    0 mod=    0
2022-04-27 23:02:41.662 [   INFO] xmltv: /usr/bin/tv_grab_fr:  broadcasts tot=    0 new=    0 mod=    0

----------------------------------------------
(Please provide the full commands you are running)
1. tv_grab_fr --configure --config-file /usr/bin/tv_grab_fr.conf
2. tv_grab_fr uses a cache to store files that have been downloaded. Please specify path to cache directory.
Directory to store tv_grab_fr cache: [/root/.xmltv/cache] : Entr
3. Select one: [0,1,2,3,4,5,6,7,8,9,10 (default=0)] 3

-------------------------------------

I use "tv_grab_ch_search", it works perfectly. 
What's wrong with that ?

**Comment by knowledgejunkie** [comment] 2022-04-28 00:20
Are you able to retry using the current stable release, which is version 1.1.2?

XMLTV 0.6.1 was released more than 3 years ago, and there have been changes to the upstream tv_grab_fr listings provider in that time.

Debian packages for XMLTV 1.1.2 are available in Debian Testing (Bookworm).

**Comment by Slim1399** [comment] 2022-04-28 04:56
I don't prefer this, but I would do it on another machine !

**Comment by honir** [comment] 2022-04-28 11:18
Duplicate of #174

**Closed by honir** 2022-04-28 11:18 UTC
